apiVersion: apps/v1
kind: Deployment
metadata:
  name: child-welfare-app
spec:
  selector:
    matchLabels:
      app: child-welfare-app
  template:
    metadata:
      labels:
        app: child-welfare-app
    spec:
      containers:
      - name: child-welfare-app
        image: child-welfare-app:latest
        imagePullPolicy: IfNotPresent

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
